# Generated by Django 2.2.1 on 2019-05-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190513_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
